### PR TITLE
increase deploy button size

### PR DESCRIPTION
**Pull request by susanev**
these appear quite small in repos, and are easy to miss.
this increases the size a bit so they stand out a bit better.
also adds a shadow for folks viewing these in github dark mode.

### CODE REVIEW

**Review by cnunciato — COMMENTED** [review]
Thanks for doing this! Button size looks good, but I'm not sure I'd want to put a fixed shadow on every button everywhere like this, as shadows are generally applied in context. (In other words, if we did this, we'd likely end up with buttons that "didn't look right" in certain situations, and have to work around it.) 

Definitely in favor of making things look right in GitHub READMEs, though! It looks like GitHub recently released a way to switch between images based on theme, so assuming we we'll want to create a dark-theme button for use on our own site, etc., something like this would probably be a more flexible way to go: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

**Comment by susanev** [comment]
@cnunciato ill drop the shadows for now then? did you take a look at them? does it look bad?

and come back later to the better approach you mentioned.

**Comment by cnunciato** [comment]
@susanev Perfect, thanks. And yep, I did, and they look fine -- it's just they may not look fine _everywhere_, yeah.

**Comment by susanev** [comment]
@cnunciato but what i dont get is that's true for every piece of style information right? what is special about a shadow to you?

**Review by caseyyh — APPROVED** [review]

**Comment by cnunciato** [comment]
@susanev I don't think so. Shadows are based on light source and relative depth (like in the z-axis sense), so how you choose to shadow something has to do with both of those factors, and both are going to vary depending on where this button (which is meant to be portable) is used. If the button were placed on a page where all of the other objects were shadowed with a particular shade of gray, a particular offset, a particular blur, etc., and the button itself had a different color, offset, and blur baked into it, it'd look strange alongside the others. So for this general reason, I'd leave the shadow bits out.

**Comment by susanev** [comment]
I know how shadows and light sources work, I did not ask what shadows are. I asked why you consider shadows fundamentally different than other styles. Including a button with no shadows in an experience with shadows is going to cause the same problem as including a button with no border in a system with borders. I fundamentally do not understand what is so concerning about shadows. I'll remove the shadow to satisfy your requirement.

**Comment by cnunciato** [comment]
> I asked why you consider shadows fundamentally different than other styles.

I was aiming to explain that, so apologies if I didn't succeed there. You're right that having a flat button in a sea of shadows might look out of place, though -- however in that case, the developer would be able to apply whatever shadow treatment made sense in that particular context, as the source image would still be a flat button.

All this said, you don't need my approval here -- you can certainly merge anyway on someone else's approval if you like. I'm just giving the review I was asked for and sharing my thought process. Feel free to merge anyway if you think keeping the shadows in is the right call, and I'll support ya.

**Pull request merged**
