### PR TITLE
Made arguments non-positional and added a silent flag

### PR DESCRIPTION
**Pull request by solidDoWant**
Silent flag will mute all non-error output if set. Now that there are two possible arguments I made them non-positional.

### CODE REVIEW

**Comment by solidDoWant** [comment]
Looks like build is failing but not due to these changes - it's failing on master as well.

**Comment by chrsmith** [comment]
Thanks for the PR @solidDoWant . CI will fail because of the way secrets in Travis CI are handled for forks of the repo. I'll take a close look at the PR and get back to you soon.

**Comment by chrsmith** [comment]
@solidDoWant thanks for your patience. Your changes look good, I'll go ahead and get them merged this evening. (I'll first do some testing in a staging environment to double check everything's on the up and up.)

**Comment by solidDoWant** [comment]
Fantastic, thank you!

**Pull request merged**
