### PR TITLE
Release recent updates 

### PR DESCRIPTION
**Pull request by cnunciato**

### CODE REVIEW

**Comment by cnunciato** [comment]
Hm -- this is a PR for production. Shouldn't the stack have been `production`?

**Comment by stack72** [comment]
Looks like there may be some oddities around stack selection in the pull-request workflow...

**Comment by stack72** [comment]
> Looks like there may be some oddities around stack selection in the pull-request workflow...
> 

Actually no, this is correct

The ref is not containing production - it's a PR so it'll be a pull based ref

refs/remotes/pull/113/merge

So it won't match the production rule 

I'm not 100% sure on the intention of this tbh... it looks like this will never work to preview production

**Comment by cnunciato** [comment]
I don't think I have the repo perms to investigate, but it looks like something's going wrong here:

https://github.com/pulumi/get.pulumi.com/pull/114/checks?check_run_id=2471692109#step:3:6

Maybe that secret isn't defined?

**Comment by leezen** [comment]
That secret is defined -- I wonder if something odd is happening w.r.t. quoting?

**Comment by cnunciato** [comment]
The plot thickens: 

image

It looks to me like `GITHUB_ENV` is just not defined in this context somehow. 🤔

**Comment by cnunciato** [comment]
Ok I think I figured this out. It's [these lines](https://github.com/pulumi/get.pulumi.com/blob/41a07ebf53ddd6f4de3e08e2c5d444b0fcce2ed7/.github/workflows/pull-request.yml#L38-L40):

```
...
preview:
  ...
  defaults:
    run:
      working-directory: infrastructure
...
```

Removing them seems to make `GITHUB_ENV` work as advertised, though no idea why.

**Comment by cnunciato** [comment]
Looks like contexts and expressions are not available in `default.run`: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun

**Comment by leezen** [comment]
@cnunciato Thanks for investigating and fixing!

**Review by leezen — APPROVED** [review]

**Pull request merged**
